# Generated by Django 2.2 on 2019-04-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.Artist'),
        ),
    ]
